#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
    php -l -d display_errors=0 $PROJECT/$FILE
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
    echo "Running Code Sniffer. Code standard PSR2."
    for FILE in $FILES
    do
        # 排除vendor文件夹下的文件
        if [[ ! $FILE == *"vendor/"* ]]; then
            ./vendor/bin/phpcs --standard=PSR12 --colors --encoding=utf-8 -n -p $FILE
            if [ $? != 0 ]
            then
                echo "Fix the error before commit!"
                echo "Run"
                echo "  ./vendor/bin/phpcs --standard=PSR2 $FILE"
                echo "for automatic fix or fix it manually."
                exit 1
            fi
        fi
    done
fi


exit $?
